language: go

go:
  - 1.12
  - master

install: true
sudo: false

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: false

before_install:
  - export GO111MODULE=on # Enable go mod
  - go mod vendor # Download deps

script:
  - go test ./... # Test
  - go build # Build