language: go

go:
  - 1.12
  - master

install: true
sudo: false

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: false

before_install:
  - export GO111MODULE=on # Enable go mod
  # - go mod init # Init go modules
  - go mod vendor # Download deps

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v -r ./vendor/) # All the .go files, excluding vendor/, .vendor-new/
  # For .vendor-new inclusion, GO_FILES=$(find . -iname '*.go' -type f | grep -v -r ./vendor/ ./.vendor-new/)
  - go get
script:
  - go test ./... # Test
  - go build # Build