language: go
go: 1.12

install: true
sudo: true

matrix:
  allow_failures:
    - go: master
  fast_finish: true

# notifications:
#   email: false

before_install:
  - sudo apt-get install systemd
  - export GO111MODULE=on # Enable go mod
  - go mod vendor # Download deps

script:
  - sudo go test ./... # Test
  - go build # Build